data_directory: "./sample_data"
img_dirname: "images"
mask_dirname: "masks"
learning_rate: 0.001
step_lr_step: 30
step_lr_gamma: 0.1
weight_decay: 0.0005
batch_size: 4
num_epochs: 100
optimizer: "sgd"
is_cuda: true
load_weights: false
path_to_model: "./sample_data"
dataset_len: -1
img_width: 1024
img_height: 1024
classes: 1
in_channels: 3
early_stopping_patience: -1
architecture: "Unet"
encoder_name: "resnet34"
encoder_weights: "imagenet"
